package com.exacttarget.wsdl.partnerapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.exacttarget.subscribersearch.web.PropertiesHelper;


/**
 * ExactTarget Partner API
 *
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-23T12:39:11.831-04:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "PartnerAPI", 
                  wsdlLocation = "https://webservice.exacttarget.com/etframework.wsdl",
                  targetNamespace = "http://exacttarget.com/wsdl/partnerAPI") 
public class PartnerAPI extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://exacttarget.com/wsdl/partnerAPI", "PartnerAPI");
    public final static QName Soap = new QName("http://exacttarget.com/wsdl/partnerAPI", "Soap");
    static {
        URL url = null;
        try {
            url = new URL(PropertiesHelper.getAppProperty("DEFAULT_WSDL_LOCATION"));
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PartnerAPI.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", PropertiesHelper.getAppProperty("DEFAULT_WSDL_LOCATION"));
        }
        WSDL_LOCATION = url;
    }

    public PartnerAPI(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PartnerAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartnerAPI() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Soap
     */
    @WebEndpoint(name = "Soap")
    public Soap getSoap() {
        return super.getPort(Soap, Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Soap
     */
    @WebEndpoint(name = "Soap")
    public Soap getSoap(WebServiceFeature... features) {
        return super.getPort(Soap, Soap.class, features);
    }

}
